# Конфигурация плагина SpeedFlash

# Настройки скорости
speed:
  multiplier: 1.0
  max-speed: 10.0
  min-speed: 0.1
  default-speed: 2.0

# Настройки эффектов
effects:
  speed_boost:
    enabled: true
    duration: 60
    amplifier: 1
  jump_boost:
    enabled: true
    duration: 60
    amplifier: 1
  invisibility:
    enabled: true
    duration: 30
    amplifier: 1
  night_vision:
    enabled: true
    duration: 120
    amplifier: 1
  damage_protection:
    enabled: true
    duration: 45
    amplifier: 1

# Настройки базы данных
database:
  enabled: false
  type: "SQLite" # SQLite или MySQL
  host: "localhost"
  port: 3306
  name: "speedflash"
  username: "root"
  password: ""

# Настройки Telegram бота
telegram:
  enabled: false
  token: "ВАШ_ТОКЕН_ТЕЛЕГРАМ"
  chat_id: "ВАШ_CHAT_ID"
  username: "имя_бота"
  broadcast-messages: true
  join-notifications: true

# Настройки сообщений
messages:
  prefix: "&bSpeedFlash &8» &7"
  no-permission: "&cУ вас нет разрешения!"
  player-only: "&cЭта команда только для игроков!"

# Настройки веб-сервера
web:
  enabled: true
  port: 8080
  api-key: "your-secret-api-key-here"
  allowed-origins:
    - "http://localhost:8080"
    - "speedflash-mc.netlify.app"

