name: Java CI with Maven

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
      
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: SpeedFlash-Plugin
        path: target/*.jar
        retention-days: 30
        
    - name: Upload to GitHub Releases
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: target/*.jar
